-- Creating and storing global variable

DECLARE @PRM_ALLOC_LEVEL AS INT
SET @PRM_ALLOC_LEVEL = 500000

DECLARE @VAL_M AS INT
DECLARE @VAL_Y AS INT
SET @VAL_M = (SELECT MONTH(END_DATE) FROM Val_Date)
SET @VAL_Y = (SELECT YEAR(END_DATE) FROM Val_Date)


DECLARE @SWITCH_ROUNDING AS INT
SET @SWITCH_ROUNDING = 1
